# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-tolbargy'
    repository: 'tolbargy/hello-world-flask'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: '$(version)'
- task: CmdLine@2
  inputs:
    script: 'sed -i "s/:latest/:$(version)/g" deployment.yml'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'deployment.yml'
    ArtifactName: 'yaml-hello-world-flask'
    publishLocation: 'Container'