version: '3.1'
services:
  back-demo-docker:
    image: back-demo-docker
    container_name: back-demo-docker
    restart: always
    build: 
      context: ./
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 82:80
